### ISSUE TITLE
test for storing data in flash after turning off the power

### ISSUE THREAD

**Issue by DmitryTyazhlov** [gev/reacthome-firmware#104]

**Comment by DmitryTyazhlov** [comment]
![IMG_3788](https://github.com/gev/reacthome-firmware/assets/69074486/20a3e9fe-bc66-4992-ac0a-3ed0dd593f8f)
очистка страницы размером килобайт занимает 32 милисекунды

**Comment by DmitryTyazhlov** [comment]
запись килобайта во флэш на gd32f330k8 занимает 11 милисекунд
![IMG_3790](https://github.com/gev/reacthome-firmware/assets/69074486/ad71dbe8-90fe-48e1-af8d-1375e44a0948)

**Comment by DmitryTyazhlov** [comment]
микроконтроллер без внешних плат и включения дополнительных внутренних переферий, при 3.1 вольте срабатывает прерывание, в нем очищается и записывается страница, емкость конденсатора 2100 мкф, время разряда с 3.1 до 2.6 вольт 48мс , до полного выключения микроконтроллера 158 мс, запись в память происходит успешно
![IMG_3792](https://github.com/gev/reacthome-firmware/assets/69074486/19bd8a19-0161-4e72-bdbe-e8bfd6d48044)
![IMG_3791](https://github.com/gev/reacthome-firmware/assets/69074486/b0bca2a0-aed5-44be-92d6-bc01b69af66b)

**Comment by DmitryTyazhlov** [comment]
конденсатор 2100мкф, порты микроконтроллера нагружены оптопарами от диммера 220в (все 12 каналов), в прерывании так же очищается страница и записывается килобайт
время от 3.1 до 2.6в 7.2мс, от 3.1 до выключения 24.6мс
при записи страница бьется (заполнена нулями)
![IMG_3794](https://github.com/gev/reacthome-firmware/assets/69074486/3b82a902-b45d-4515-9eff-a8e08f69fb11)
![IMG_3795](https://github.com/gev/reacthome-firmware/assets/69074486/bb8279bf-9543-4c60-b445-85c828bcfec3)

**Comment by gev** [comment]
и   GD32F450 нужно померить тоже, использовать, соответственно, его длину страницы
